# Generated by Django 4.2.10 on 2024-02-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='People',
        ),
    ]
